[project]
name = "reefpulse-backend"
version = "0.1.0"
description = "AI-powered reef health monitoring backend"
authors = [
    {name = "Ashwin Gururaj"}
]
license = "MIT"
requires-python = ">=3.11,<4.0"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
